### ISSUE TITLE
Networking API

### ISSUE THREAD

**Issue by VibAltekar** [huggingface/snapchat-lens-api#1]
Does anyone know if there are plans to incorporate a network request API in the snapchat lens API? It would be great if I could make a GET request depending on what I take a snapchat of.

**Comment by julien-c** [comment]
I have no idea.

There are quite a few threads on the official Forum about this though:
https://support.lensstudio.com/hc/en-us/community/posts/360018251566-Lense-s-Network-Connectivity
https://support.lensstudio.com/hc/en-us/community/posts/360042984932-Feature-request-play-network-backed-AudioTrackAssets

**Comment by VibAltekar** [comment]
Ah unfortunate! Hopefully they get to it soon!

It seems like Spark AR (FB's version of lens studio) has networking functionality. 
https://developers.facebook.com/docs/ar-studio/reference/classes/networkingmodule/

**Comment by julien-c** [comment]
Yes indeed
